### ISSUE TITLE
Getting undefined, what am i missing?

### ISSUE THREAD

**Issue by captainreptile** [manolodd/mosquitto-pbkdf2#3]
Hello, 
Thanks for the gr8 module!
I have installed this on ionic, but i don't get any generated password am i missing something?

After npm install i added the import:
`import * as MosquittoPBKDF from 'mosquitto-pbkdf2';`

`
MosquittoPBKDF.createPasswordAsync('Password', this.callback);
console.log("pbkdf2-1",this.callback);
`
And tried:
` console.log("pbkdf2-3",MosquittoPBKDF.createPasswordAsync('Password', this.callback);
`

Much appreciated for your answer.

**Comment by captainreptile** [comment]
After sometime i solved it, i searched for hint in test.js
working code:
`    MosquittoPBKDF.createPasswordAsync(password, doSomethingWhenPBKDF2PasswordIsCreated);
      function doSomethingWhenPBKDF2PasswordIsCreated(pbkdf2Password) {
              console.log("New password created: " + pbkdf2Password);
      }
`

**Comment by manolodd** [comment]
Great!
